compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.3.1.cjs
