# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

on:
  push:
    branches:
      - main
  pull_request:

name: Build

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-all:
    name: Build all packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      - name: Install dependencies with Bun
        run: |
          bun install --frozen-lockfile
        shell: bash

      - uses: actions/cache/restore@v4
        with:
          path: |
            **/dist/
            **/build/
            **/.next/
            **/.ultra.cache.json
          key: ${{ runner.os }}-ultra-v1-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ultra-v1-${{ github.head_ref || github.ref_name }}-
            ${{ runner.os }}-ultra-v1-main-

      - name: Build the entire monorepo
        run: |
          bun run build

      - uses: actions/cache/save@v4
        if: github.event_name == 'push'
        with:
          path: |
            **/dist/
            **/build/
            **/.next/
            **/.ultra.cache.json
          key: ${{ runner.os }}-ultra-v1-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
